version: "3.8"

services:
  database:
    image: postgres:16.2-alpine
    container_name: database
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backendfight
    ports:
      - 5432:5432
    volumes:
      - ./containers/postgresql.conf:/etc/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "200MB"

  api1: &api1
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: api1
    restart: always
    environment: &env_api1
      DATABASE_DSN: postgres://postgres:postgres@database/backendfight?sslmode=disable
    ports:
      - 4001:4000
    depends_on:
      - database
    command: ["migrate_and_release"]
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '150MB'
  
  api2:
    <<: *api1
    container_name: api2
    depends_on:
      - api1
    environment:
      <<: *env_api1
    ports:
      - 4002:4000
    command: ["release"]

  nginx:
    image: nginx:1.25.3-alpine
    restart: always
    container_name: nginx
    volumes:
      - ./containers/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'
